name: pta_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - gitpython
  - scipy
  - pip:
      - ./data_combination_pipeline_module_with_pta_qc_hook.zip
      - ./pta_qc_packaged.zip
      - libstempo
